CREATE TABLE IF NOT EXISTS products(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  body VARCHAR(255),
  imgUrl VARCHAR(255),
  title VARCHAR(255),
  published TINYINT
) DEFAULT charset utf8;